// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = {
	/**
	 * app started
	 */
	'startup': string
	'locale': {	
		/**
		 * choose locale...
		 */
		'choose': string
		/**
		 * Selected locale:
		 */
		'selectedLocale': string
	}
	'greeting': {	
		/**
		 * Hello {name}!
		 * @param {string} name
		 */
		'message': RequiredParams1<'name'>
		/**
		 * Your name:
		 */
		'label': string
	}
	/**
	 * Today is {date|weekday}
	 * @param {Date} date
	 */
	'today': RequiredParams1<'date|weekday'>
	'counter': {	
		/**
		 * Clicks:
		 */
		'clicks': string
	}
}

export type TranslationFunctions = {
	/**
	 * app started
	 */
	'startup': () => LocalizedString
	'locale': {	
		/**
		 * choose locale...
		 */
		'choose': () => LocalizedString
		/**
		 * Selected locale:
		 */
		'selectedLocale': () => LocalizedString
	}
	'greeting': {	
		/**
		 * Hello {name}!
		 */
		'message': (arg: { name: string }) => LocalizedString
		/**
		 * Your name:
		 */
		'label': () => LocalizedString
	}
	/**
	 * Today is {date|weekday}
	 */
	'today': (arg: { date: Date }) => LocalizedString
	'counter': {	
		/**
		 * Clicks:
		 */
		'clicks': () => LocalizedString
	}
}

export type Formatters = {
	'weekday': (value: Date) => unknown
}

type Param<P extends string> = `{${P}}`

type Params1<P1 extends string> =
	`${string}${Param<P1>}${string}`

type RequiredParams1<P1 extends string> =
	| Params1<P1>
